site_name: site name goes here
pages:
  - Home: 'index.md'
  - k8s cookbook:
    - cheatsheet: 'k8s/cheatsheet/index.md'
    - compare: 'k8s/compare/index.md'
  - Tools:
    - SSH: 'tools/ssh.md'
    - Git: 'tools/git.md'
  - Configuration:
    - CA Certificates: 'config/certificates/README.md'
theme:
  name: 'material'
